name: Update README

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update README.md with current timestamp
      run: |
        TIMESTAMP=$(date)
        sed -i "s/Updated at .*/Updated at $TIMESTAMP/" README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update README with current timestamp"
        git push
